# Global stages for the pipeline
stages:
  - scheduled

.litmus-test-base:
  stage: scheduled
  image: python:3.11-alpine
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install requests
  artifacts:
    paths:
      - litmus_test_results/
    expire_in: 1 week

dev-litmus-test:
  extends:
    - .litmus-test-base
  script:
    - |
      python benchmark.py \
        "$DEV_LITMUS_BASE_URL" \
        "gitlab-run" \
        "${DEV_ENDPOINT}" \
        "${TEST_SUITES:-aiguardian-baseline-tests}" \
        "${NUM_OF_PROMPTS:-5}" \
        "$DEV_LITMUS_API_KEY" \
        "${INTERVAL:-10}" \
        "${TIMEOUT:-600}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $JOB_ENV == "dev"

stg-litmus-test:
  extends:
    - .litmus-test-base
  script:
    - |
      python benchmark.py \
        "$LITMUS_BASE_URL" \
        "gitlab-run" \
        "${ENDPOINT}" \
        "${TEST_SUITES:-aiguardian-baseline-tests}" \
        "${NUM_OF_PROMPTS:-5}" \
        "$LITMUS_API_KEY" \
        "${INTERVAL:-10}" \
        "${TIMEOUT:-600}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $JOB_ENV == "stg"
