name: Litmus Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Benchmark
        uses: dsaidgovsg/aiguardian-litmus-test@v0.0.9
        with:
          base_url: ${{ vars.LITMUS_BASE_URL }}
          run_name: ${{ github.run_id }}-${{ github.run_attempt }}
          endpoint: ${{ vars.ENDPOINT }}
          cookbook: ${{ vars.COOKBOOK }}
          num_of_prompts: ${{ vars.NUM_OF_PROMPTS || '1'}}
          api_key: ${{ secrets.LITMUS_KEY }}
          debug_mode: ${{ vars.DEBUG_MODE || 'false' }}