name: Litmus Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-litmus-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Litmus Test
        shell: bash
        env:
          DEBUG: 'FALSE'
        run: |
          python benchmark.py \
            "${{ vars.LITMUS_BASE_URL }}" \
            "run_${{ github.run_id }}_${{ github.run_attempt }}" \
            "${{ vars.ENDPOINT }}" \
            "${{ vars.TEST_SUITES }}" \
            "${{ vars.NUM_OF_PROMPTS || '0'}}" \
            "${{ secrets.LITMUS_API_KEY }}"