name: Litmus Test Dev

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Endpoint Name"
        required: false
      test_suites:
        description: "Test Suites (comma-separated)"
        default: "aiguardian-baseline-tests"
        required: false
      num_of_prompts:
        description: "Number of Prompts"
        default: "5"
        required: false
      api_key:
        description: "key"
        default: "abcd"
        required: false
      timeout:
        description: "Timeout (in seconds)"
        default: "600"
        required: false

jobs:
  run-litmus-dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 'Litmus Test - ${{github.event.inputs.endpoint||vars.DEV_ENDPOINT}} - ${{github.event.inputs.test_suites||vars.TEST_SUITES}} - ${{github.event.inputs.num_of_prompts||vars.NUM_OF_PROMPTS}}'
        shell: bash
        env:
          DEBUG: 'FALSE'
        run: |
          python benchmark.py \
            "${{ vars.DEV_LITMUS_BASE_URL }}" \
            "github-run" \
            "${{ github.event.inputs.endpoint || vars.DEV_ENDPOINT }}" \
            "${{ github.event.inputs.test_suites || vars.TEST_SUITES }}" \
            "${{ github.event.inputs.num_of_prompts || vars.NUM_OF_PROMPTS}}" \
            "${{ github.event.inputs.api_key || secrets.DEV_LITMUS_API_KEY }}"\
            "${{ vars.INTERVAL || '10' }}" \
            "${{ github.event.inputs.timeout || vars.TIMEOUT || '180'}}"

      - name: Upload Litmus Test Results
        uses: actions/upload-artifact@v4
        with:
          name: litmus-dev-test-results
          path: litmus_dev_test_results